config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  root 'welcome#index'

  resources :companies
  resources :opportunities

  get 'profile', to: 'users#profile', as: 'profile'


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user

  has_many :opportunities, dependent: :destroy

  has_attached_file :logo, styles: { medium: "200x200#",small: "150x150#",thumb: "100x100#" }

  validates :name, presence: true, length: {minimum: 3}
  validates :website, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 75, maximum: 1000}
  validates_attachment_content_type :logo, content_type:  /\Aimage\/.*\Z/, size: { in: 0..1.5.megabytes }
  validates :company_size, presence: true
  validates :founded, presence: true, length: {minimum: 4, maximum: 4}
  validates :headquarters, presence: true, length: {minimum: 3}

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
  belongs_to :company

  has_attached_file :logo, styles: { medium: "200x200#",small: "150x150#",thumb: "100x100#" }

  validates :name, presence: true, length: {minimum: 3}
  validates :location, presence: true, length: {minimum: 3}
  validates :description, presence: true, length: {minimum: 75, maximum: 1000}
  validates_attachment_content_type :logo, content_type:  /\Aimage\/.*\Z/, size: { in: 0..1.5.megabytes }
  validates :responsibilities, presence: true, length: {minimum: 75, maximum: 1000}
  validates :duration, presence: true, length: {minimum: 3}
  validates :hourly_rate, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :companies, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true, length: { minimum: 3, maximum: 25 }
  validates :last_name, presence: true, length: { minimum: 3, maximum: 25 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_company, only: [:edit, :update, :show, :destroy]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
		@company.user = current_user
		if @company.save
			flash[:success] = "Article was successfully created"
			redirect_to company_path(@company)
		else
			render 'new'
		end
  end

  def edit
  end

  def show
  end

  def update
    if @company.update(company_params)
			flash[:success] = "Company was successfully updated"
			redirect_to company_path(@company)
		else
			render 'edit'
		end
  end

  def destroy
  end


  private
  def set_company
    @company = Company.find(params[:id])
  end

  def company_params
    params.require(:company).permit(:name, :website, :description, :company_size, :founded, :headquarters, :logo)
  end

  def require_same_user
		if current_user != @company.user
			flash[:danger] = "You can only edit your own company"
			redirect_to root_path
		end
	end

end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_opportunity, only: [:edit, :update, :show, :destroy]
  before_action :require_company_owner, only: [:edit, :update, :destroy]

  def index
    @opportunities = Opportunity.all
  end

  def new
    # redirect to root path if user has no company yet
    if current_user.companies.empty?
      flash[:danger] = "You must create a company before adding an internship"
      redirect_to new_company_path
    end

    @opportunity = Opportunity.new
  end

  def create
    @opportunity = Opportunity.new(opportunity_params)
    # we need to see if the company belongs to the user that is signed in
    if current_user.companies.exists?(params[:opportunity][:company_id])
      @opportunity.company = Company.find(params[:opportunity][:company_id])
      if @opportunity.save
  			flash[:success] = "Internship was successfully created"
  			redirect_to opportunity_path(@opportunity)
  		else
  			render 'new'
  		end
    else
      flash[:danger] = "You can not create an internship for this company"
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @opportunity.update(opportunity_params)
			flash[:success] = "Company was successfully updated"
			redirect_to opportunity_path(@opportunity)
		else
			render 'edit'
		end
  end

  def destroy
  end

  private

  def set_opportunity
    @opportunity = Opportunity.find(params[:id])
  end

  def opportunity_params
    params.require(:opportunity).permit(:name, :description, :location, :responsibilities, :duration, :hourly_rate)
  end

  def require_company_owner
    unless current_user.companies.exists?(@opportunity.company)
		 flash[:danger] = "You can only edit your own internships"
		 redirect_to root_path
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def profile
  
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/companies/_form.html.haml
.container.opportunity-card
  = render 'shared/errors', obj: @company
  .row
    .col-md-10.col-md-offset-1
      %ul.ut-card
        %li.panel-body
          %h2.text-center= form_header
          %hr.col-md-10.col-md-offset-1
          = form_for(@company, :html => {class: "form-horizontal", role: "form" }) do |f|

            .form-group
              .control-label.col-md-2
                = f.label :name
                %br/
              .col-md-9
                = f.text_field :name, class: "form-control", placeholder: "Company name", autofocus: true
            .form-group
              .control-label.col-md-2
                = f.label :website
                %br/
              .col-md-9
                = f.text_field :website, class: "form-control", placeholder: "Website"
            .form-group
              .control-label.col-md-2
                = f.label :description
                %br/
              .col-md-9
                = f.text_area :description, rows: 4, class: "form-control", placeholder: "Company description"
            .form-group
              .control-label.col-md-2
                = f.label :logo
                %br/
              .col-md-9
                = f.file_field :logo
            .form-group
              .control-label.col-md-2
                = f.label :company_size
                %br/
              .col-md-9
                = f.number_field :company_size, class: "form-control", placeholder: "Company size"
            .form-group
              .control-label.col-md-2
                = f.label :founded
                %br/
              .col-md-9
                = f.number_field :founded, class: "form-control", placeholder: "Founded"
            .form-group
              .control-label.col-md-2
                = f.label :headquarters
                %br/
              .col-md-9
                = f.text_field :headquarters, class: "form-control", placeholder: "Headquarters"
            .form-group
              .col-md-offset-2.col-md-10
                = f.submit(class: "btn ut-btn ut-btn-blue")

app/views/companies/edit.html.haml
= render 'form', form_header: "Update Company"

app/views/companies/index.html.haml
%h1.text-center Companies

.internships-container
  - @companies.each do |company|
    .col-md-4.col-sm-6
      %ul.ut-card
        %li.panel-body
          %div.col-md-12.ut-card-heading
            %div.col-md-3
              -# %img.img-rounded.img-responsive{src: "http://placehold.it/150x150"}
              = image_tag company.logo.url(:thumb)
            %div.col-md-9
              %h3= link_to company.name, company_path(company)
              %p
                %strong
                  %i.fa.fa-globe
                  = company.website
            %ul.list-inline.col-md-12.ut-icon-container
              %li
                %i.fa.fa-users
                = company.company_size
              %li
                %i.fa.fa-building
                = company.headquarters
              %li
                %i.fa.fa-angle-right
                = "Founded in #{company.founded}"
            %div.col-md-12.ut-card-description
              %p= company.description.truncate(75)

app/views/companies/new.html.haml
= render 'form', form_header: "Create Company"

app/views/companies/show.html.haml
.container.opportunity-card
  .row
    .col-md-10.col-md-offset-1
      %ul.ut-card
        %li.panel-body
          %div.col-md-12
            %div.col-md-3
              -# %img.img-rounded.img-responsive{src: "http://placehold.it/500x500"}
              =image_tag @company.logo.url(:small)
            %div.col-md-9
              %h1= @company.name
              %h3
                %strong
                %i.fa.fa-globe
                = @company.website
            %ul.list-inline.col-md-12.ut-icon-container
              %li
                %i.fa.fa-users
                = @company.company_size
              %li
                %i.fa.fa-building
                = @company.headquarters
              %li
                %i.fa.fa-angle-right
                = "Founded in #{@company.founded}"
            %div.col-md-12.ut-card-description
              %h3 Description
              %p= simple_format(@company.description)
            %div.col-md-12.ut-card-description
            %div.col-md-12
              -if user_signed_in? && current_user == @company.user
                = link_to "Add internship", new_opportunity_path, class: "btn ut-btn ut-btn-green"
              - if user_signed_in? && current_user.companies.exists?(@company)
                = link_to "Edit", edit_company_path(@company), class: "btn btn-link"


- unless @company.opportunities.empty?
  %h1.text-center= "#{@company.name} internships"

  .internships-container
    - @company.opportunities.each do |o|
      .col-md-4.col-sm-6
        %ul.ut-card
          %li.panel-body
            %div.col-md-12.ut-card-heading
              %div.col-md-3
                -# %img.img-rounded.img-responsive{src: "http://placehold.it/150x150"}
                =image_tag @company.logo.url
              %div.col-md-9
                %h3= link_to o.name, opportunity_path(o)
                %p
                  %strong= link_to o.company.name, company_path(o.company)
              %ul.list-inline.col-md-12.ut-icon-container
                %li
                  %i.fa.fa-eur
                  = "#{number_with_precision(o.hourly_rate, precision: 2)}/hour"

                %li
                  %i.fa.fa-clock-o
                  = "Updated #{o.updated_at.strftime('%d-%m-%Y')}"
                %li
                  %i.fa.fa-map-marker
                  = o.location
              %div.col-md-12.ut-card-description
                %p= o.description.truncate(75)

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top#unitern-navbar
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/") Unitern
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav.navbar-left
        %li= link_to "Companies", companies_path
        %li= link_to "Internships", opportunities_path
      %ul.nav.navbar-nav.navbar-right
        %ul.nav.navbar-nav.navbar-left
          - if user_signed_in?
            %li.dropdown
              %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                = current_user.email
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Profile", profile_path
                %li.divider{:role => "separator"}
                %li= link_to "Logout", destroy_user_session_path, method: :delete
            %li.dropdown.create-new
              %a.dropdown-toggle.btn.ut-btn.ut-btn-green{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                Create New
                %span.caret
              %ul.dropdown-menu
                %li= link_to "Company", new_company_path
                - unless current_user.companies.empty?
                  %li.divider{:role => "separator"}
                  %li= link_to "Internship", new_opportunity_path
          - else user_signed_in?
            %li.btn.ut-btn.ut-btn-green.not-auth= link_to "Log in", new_user_session_path
            %li.btn.ut-btn.ut-btn-blue.not-auth= link_to "Sign up", new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Unitern"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    = bootstrap_flash
    = render "layouts/header"


    = yield




    -# %footer
    -#   %p &copy; UniTern 2016

  -# = debug(params) if Rails.env.development?

app/views/opportunities/_form.html.haml
.container.opportunity-card
  = render 'shared/errors', obj: @opportunity
  .row
    .col-md-10.col-md-offset-1
      %ul.ut-card
        %li.panel-body
          %h2.text-center= form_header
          %hr.col-md-10.col-md-offset-1
          = form_for(@opportunity, :html => {class: "form-horizontal", role: "form" }) do |f|
            .form-group
              .control-label.col-md-2
                = f.label :company_id, "Select Company"
                %br/
              .col-md-9
                = f.select :company_id, options_from_collection_for_select(current_user.companies, 'id', 'name', current_user.companies[0].id), {}, {required: 'true', autofocus: 'true', class: 'form-control',}
            .form-group
              .control-label.col-md-2
                = f.label :name
                %br/
              .col-md-9
                = f.text_field :name, class: "form-control", placeholder: "Internship name"
            .form-group
              .control-label.col-md-2
                = f.label :location
                %br/
              .col-md-9
                = f.text_field :location, class: "form-control", placeholder: "Location"
            .form-group
              .control-label.col-md-2
                = f.label :duration
                %br/
              .col-md-9
                = f.text_field :duration, class: "form-control", placeholder: "How long is the internship for"
            .form-group
              .control-label.col-md-2
                = f.label :hourly_rate
                %br/
              .col-md-9
                = f.number_field :hourly_rate, class: "form-control", placeholder: "Hourly rate", step: "any"
            .form-group
              .control-label.col-md-2
                = f.label :description
                %br/
              .col-md-9
                = f.text_area :description, rows: 6, class: "form-control", placeholder: "Description"
            .form-group
              .control-label.col-md-2
                = f.label :responsibilities
                %br/
              .col-md-9
                = f.text_area :responsibilities, rows: 4, class: "form-control", placeholder: "Responsibilities"
            .form-group
              .col-md-offset-2.col-md-10
                = f.submit(class: "btn ut-btn ut-btn-blue")

app/views/opportunities/edit.html.haml
.container.opportunity-card
  = render 'shared/errors', obj: @opportunity
  .row
    .col-md-10.col-md-offset-1
      %ul.ut-card
        %li.panel-body
          %h2.text-center Edit Internship
          %hr.col-md-10.col-md-offset-1
          = form_for(@opportunity, :html => {class: "form-horizontal", role: "form" }) do |f|
            .form-group
              .control-label.col-md-2
                = f.label :name
                %br/
              .col-md-9
                = f.text_field :name, class: "form-control", placeholder: "Internship name"
            .form-group
              .control-label.col-md-2
                = f.label :location
                %br/
              .col-md-9
                = f.text_field :location, class: "form-control", placeholder: "Location"
            .form-group
              .control-label.col-md-2
                = f.label :duration
                %br/
              .col-md-9
                = f.text_field :duration, class: "form-control", placeholder: "How long is the internship for"
            .form-group
              .control-label.col-md-2
                = f.label :hourly_rate
                %br/
              .col-md-9
                = f.number_field :hourly_rate, class: "form-control", placeholder: "Hourly rate", step: "any"
            .form-group
              .control-label.col-md-2
                = f.label :description
                %br/
              .col-md-9
                = f.text_area :description, rows: 6, class: "form-control", placeholder: "Description"
            .form-group
              .control-label.col-md-2
                = f.label :responsibilities
                %br/
              .col-md-9
                = f.text_area :responsibilities, rows: 4, class: "form-control", placeholder: "Responsibilities"
            .form-group
              .col-md-offset-2.col-md-10
                = f.submit "Update Internship", class: "btn ut-btn ut-btn-blue"

app/views/opportunities/index.html.haml
%h1.text-center Internships

.internships-container
  - @opportunities.each do |o|
    .col-md-4.col-sm-6
      %ul.ut-card
        %li.panel-body
          %div.col-md-12.ut-card-heading
            %div.col-md-3
              -# %img.img-rounded.img-responsive{src: "http://placehold.it/150x150"}
              = image_tag o.company.logo.url(:thumb)
            %div.col-md-9
              %h3= link_to o.name, opportunity_path(o)
              %p
                %strong= link_to o.company.name, company_path(o.company)
            %ul.list-inline.col-md-12.ut-icon-container
              %li
                %i.fa.fa-eur
                = "#{number_with_precision(o.hourly_rate, precision: 2)}/hour"

              %li
                %i.fa.fa-clock-o
                = "Updated #{o.updated_at.strftime('%d-%m-%Y')}"
              %li
                %i.fa.fa-map-marker
                = o.location
            %div.col-md-12.ut-card-description
              %p= o.description.truncate(75)

app/views/opportunities/new.html.haml
= render "form", form_header: "Create Internship"

app/views/opportunities/show.html.haml
.container.opportunity-card
  .row
    .col-md-10.col-md-offset-1
      %ul.ut-card
        %li.panel-body
          %div.col-md-12
            %div.col-md-3
              -# %img.img-rounded.img-responsive{src: "http://placehold.it/500x500"}
              =image_tag @opportunity.company.logo.url(:small)
            %div.col-md-9
              %h1= @opportunity.name
              %h3
                %strong= link_to @opportunity.company.name, company_path(@opportunity.company)
            %ul.list-inline.col-md-12.ut-icon-container
              %li
                %i.fa.fa-eur
                = "#{number_with_precision(@opportunity.hourly_rate, precision: 2)}/hour"

              %li
                %i.fa.fa-clock-o
                = "Updated #{@opportunity.updated_at.strftime('%d-%m-%Y')}"
              %li
                %i.fa.fa-map-marker
                = @opportunity.location
              %li
                %i.fa.fa-user
                = "#{@opportunity.company.user.first_name} #{@opportunity.company.user.last_name}"
            %div.col-md-12.ut-card-description
              %h3 Description
              %p= simple_format(@opportunity.description)
            %div.col-md-12.ut-card-description
              %h3 Responsibilities
              %p= simple_format(@opportunity.responsibilities)
            %div.col-md-12
              = link_to "Apply", "#", class: "btn ut-btn ut-btn-green"
              - if user_signed_in? && current_user.companies.exists?(@opportunity.company)
                = link_to "Edit", edit_opportunity_path(@opportunity), class: "btn btn-link"

app/views/shared/_errors.html.haml
.row.col-sm-10.col-sm-offset-1

  - if obj.errors.any?
    .row
      .col-md-12
        .panel.panel-danger
          .panel-heading
            %h2.panel-title
              = pluralize(obj.errors.count, "error")
              prohibited this resource from being saved:
            .panel-body
              %ul
                - obj.errors.full_messages.each do |msg|
                  %li= msg

app/views/users/profile.html.haml
%h1.text-center Profile
%h3.text-center= current_user.first_name + " " + current_user.last_name + " (#{current_user.email})"

%p.text-center= link_to 'Edit Account', edit_user_registration_path, class: 'btn btn-link'

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.haml
.jumbotron#welcome-page
  .container
  